### ISSUE TITLE
Xamarin.Forms Android SignIn Activity .NET Standard problem?

### ISSUE THREAD

**Issue by dimitrijevic** [Microsoft/healthvault-dotnetstandard-sdk#72]
I've got a problem just initiating activity object from SignInActivity.cs on a Android Xamarin.Forms app.

Here's the log:
`07-09 09:10:40.919 I/MonoDroid(15138): UNHANDLED EXCEPTION:`
`07-09 09:10:41.009 I/MonoDroid(15138): System.ArgumentNullException: Value cannot be null.`
`07-09 09:10:41.009 I/MonoDroid(15138): Parameter name: value`
`07-09 09:10:41.009 I/MonoDroid(15138):   at System.String.IndexOf (System.String value, System.Int32 startIndex, System.Int32 count, System.StringComparison comparisonType) [0x00003] in <3fd174ff54b146228c505f23cf75ce71>:0 `
`07-09 09:10:41.009 I/MonoDroid(15138):   at System.String.IndexOf (System.String value, System.StringComparison comparisonType) [0x00009] in <3fd174ff54b146228c505f23cf75ce71>:0 `
`07-09 09:10:41.009 I/MonoDroid(15138):   at System.String.Contains (System.String value) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0` 
`07-09 09:10:41.009 I/MonoDroid(15138):   at Microsoft.HealthVault.Client.Platform.Android.SignInActivity+SignInWebViewClient.OnPageFinished (Android.Webkit.WebView view, System.String url) [0x00008] in C:\agent-onesdk-1\_work\11\s\Microsoft.HealthVault.Client.Android\SignInActivity.cs:97 `
`07-09 09:10:41.009 I/MonoDroid(15138):   at Android.Webkit.WebViewClient.n_OnPageFinished_Landroid_webkit_WebView_Ljava_lang_String_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_view, System.IntPtr native_url) [0x00017] in <9ab9faae1b4b4f0da28e7c4ac61e2c78>:0 `
`07-09 09:10:41.009 I/MonoDroid(15138):   at (wrapper dynamic-method) System.Object:e17947bc-5ab0-484b-b7b1-a4b878b97cd7 (intptr,intptr,intptr,intptr)`
`07-09 09:10:41.059 I/dalvikvm(15138): Could not find method java.lang.Throwable.<init>, referenced from method android.runtime.JavaProxyThrowable.<init>`

Guess you're not null checking when activity object gets used, but I'm unsure where do you set it, guess it's passed into a constructor that way...I'll check on iOS this week, but the same code works on UWP, and I can post it if needed...it's mostly the code from the Build'17 HealthVault presentation used in the core lib (I thought it might have been the lack of modernhttpclient in that core .net standard 1.4 lib, as I've had such trouble before on Anroid when doing http requests without it, but manual nuget add does the same)

**Comment by dspractice** [comment]
We have Xamarin forms samples for the SDK [here ](https://github.com/Microsoft/healthvault-samples/tree/master/dotNETStandard/HealthVault.Mobile/cs) The samples in that repo should run, can you verify your implementation ?

**Comment by dimitrijevic** [comment]
Sorry I wasn't checking this, but now I tried your sample, and it works after a 1.66.20706.2-preview nuget upgrade (I've submitted a pull request), so I'll be using that code in the future (the only thing seemingly different (beside the upgraded nuget now) is that your AuthenticateAsync() is called within a LoadAsync:

```
await LoadAsync(async () =>
            {
                await _connection.AuthenticateAsync();
            });
```

so I might take a look if that LoadAsync fixes my code's problems on Android (if that is the case this is/was a non-issue). Thank you all the same.

**Comment by jhutchings1** [comment]
Hi Dimitri, the current version of ActionPlans APIs are supported the Plan data type, but there are some other related data types we recommend that you check. Please see this documentation for more info: https://docs.microsoft.com/en-us/healthvault/getting-started/configuring-new-app-acc.
